<?php

namespace backend\models;

use Yii;
use yii\web\UploadedFile;
use yii\imagine\Image;


/**
 * This is the model class for table "Publish".
 *
 * @property integer $id
 * @property string $title
 * @property string $short_desc
 * @property string $image
 * @property string $content
 * @property integer $active
 * @property string $created_at
 * @property string $updated_at
 */
class Publish extends \yii\db\ActiveRecord
{

    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Publish';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'short_desc', 'content', 'active', 'date_publish', 'url_tag'], 'required'],
            ['url_tag', 'checkMyUniqunessInTag'],
            [['short_desc', 'content'], 'string'],
            [['active'], 'integer'],
            [['id', 'created_at', 'updated_at'], 'safe'],
            [['title', 'image'], 'string', 'max' => 255],
            [['file'], 'image']
        ];
    }


    public function checkMyUniqunessInTag($attribute, $params) {

        $count = Yii::$app->db->createCommand("SELECT COUNT(*) FROM  publish WHERE id <> '".$this->id."' AND url_tag LIKE '".$this->url_tag."'")->queryScalar();
        if($count>0) {
            $this->addError($attribute, 'This password is forbidden. Please try another.');
            return false;
        } else return true;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '№',
            'title' => 'Заголовок',
            'short_desc' => 'Короткий опис',
            'image' => 'Картинка 360х220px  ',
            'content' => 'Повний опис',
            'active' => 'Статус',
            'url_tag'=>'URL тег',
            'date_publish'=>'Дата публікації',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {

            //-- remove old files
            $model_old =  Publish::findOne($this->id);
            $dir = Yii::getAlias('@type_images').'/publish/';
            if($model_old) {
                if (file_exists($dir.$model_old->image)) {
                    @unlink($dir.$model_old->image);
                }
            }
            //--

            if (file_exists($dir.$this->image)) {
                @unlink($dir.$this->image);
            }
            $this->image = strtotime('now').'_'.Yii::$app->getSecurity()->generateRandomString(6).'.'.$file->extension;
            $file->saveAs($dir.$this->image);
            Image::thumbnail($dir.$this->image, 328, 200)->save($dir.$this->image, ['quality' => 90]);

        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    public function getSmallImage() {
        if($this->image){
            if ($this->image) {
                return /*str_replace('admin', '', Url::home(true)).*/'http://frontend.dev/uploads/publish/'.$this->image;
            }
        }
    }

}
